# Generated by Django 2.1.5 on 2019-01-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('name', models.CharField(default='', max_length=128, verbose_name='название')),
                ('description', models.TextField(default='', help_text='Не более 2048 знаков.', max_length=2048, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.PositiveIntegerField(choices=[(5, 'Экскурсия')], default=5, verbose_name='тип события')),
                ('recursive', models.BooleanField(default=False, verbose_name='повторяющиеся')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EventDatetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('datetime', models.DateTimeField(null=True, verbose_name='date and time')),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_set', to='clndr.Event')),
            ],
            options={
                'verbose_name': 'datetime',
                'verbose_name_plural': 'datetime set',
                'ordering': ('datetime',),
            },
        ),
    ]
