# Generated by Django 2.1.5 on 2019-01-23 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clndr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('text', models.TextField(default='', help_text='Не более 2048 символов.', max_length=2048, verbose_name='текст отзыва')),
                ('show', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'verbose_name': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('datetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clndr.EventDatetime')),
            ],
            options={
                'verbose_name_plural': 'members',
                'verbose_name': 'member',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('name', models.CharField(default='', max_length=128, verbose_name='название')),
                ('short_description', models.TextField(default='', verbose_name='краткое описание')),
                ('description', models.TextField(default='', verbose_name='описание')),
                ('type', models.PositiveIntegerField(choices=[(5, 'Экскурсия')], default=5, verbose_name='тип события')),
            ],
            options={
                'verbose_name_plural': 'templates',
                'verbose_name': 'template',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('alt', models.CharField(blank=True, default='', max_length=128, verbose_name='alternate text')),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='clndr.Template')),
            ],
            options={
                'verbose_name_plural': 'images',
                'verbose_name': 'image',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='template',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clndr.TemplateImage', verbose_name='главное изображени'),
        ),
        migrations.AddField(
            model_name='member',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clndr.Event'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='clndr.Event'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clndr.Template'),
        ),
    ]
