# Generated by Django 2.1.5 on 2019-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0002_auto_20190123_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification time')),
                ('text', models.CharField(default='', max_length=64, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'ограничение',
                'verbose_name_plural': 'ограничения',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(default='', max_length=2048, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_by_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='clndr.Restriction'),
        ),
    ]
