# Generated by Django 2.1.5 on 2019-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0003_auto_20190124_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriction',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='описание'),
        ),
    ]
