# Generated by Django 2.1.5 on 2019-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0005_auto_20190127_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdatetime',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
