# Generated by Django 2.1.5 on 2019-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0006_eventdatetime_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdatetime',
            name='free',
            field=models.BooleanField(default=True, verbose_name='свободно'),
        ),
    ]
