# Generated by Django 2.1.5 on 2019-02-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0008_auto_20190127_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='комментарий'),
        ),
    ]
