# Generated by Django 2.1.5 on 2019-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0009_auto_20190207_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='map_addr',
            field=models.TextField(default='', verbose_name='Координаты YnadexMaps'),
        ),
    ]
