# Generated by Django 2.1.5 on 2019-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0010_template_map_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='map_addr',
            field=models.CharField(default='', max_length=256, verbose_name='Координаты YandexMaps'),
        ),
    ]
