# Generated by Django 2.1.5 on 2019-01-09 15:25

import django.contrib.sites.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyFlatPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'flat page',
                'verbose_name_plural': 'flat pages',
                'default_permissions': (),
                'ordering': ('url',),
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.CreateModel(
            name='ProxySite',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'default_permissions': (),
                'ordering': ('domain',),
            },
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
